name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run 
      - run : npm run --prefix cypress/intergration
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
         ## build: npm run build
          start: npm start